Repository HishamWattar/cooks-kingdom, pull requests merged in 2023-07, with the labels that each got.

#20 Feature/order schema
  src/models/order.js
Labels: Schema

#21 Add cart model with cartItem subdocument schema
  src/__tests__/index.js
  src/models/cart.js
Labels: Schema

#23 Setup server and add MongoDB connection with env variable
  .env
  src/__tests__/index.js
  src/app.js
  src/db/connection.js
Labels: setup

#27 Feature: add review schema
  src/models/review.js
Labels: Schema

#38 feature: facebook auth
  .env
  package-lock.json
  package.json
  src/__tests__/auth.test.js
  src/config/passport.js
  src/db/connection.js
  src/routes/auth.js
  yarn.lock
Labels: authentication

#66 Ahmadalashtar/issue46 2
  .env
  package-lock.json
  package.json
  src/__tests__/admin.test.js
  src/__tests__/dish.test.js
  src/controllers/dish.js
  src/docs/Dish/dish.yaml
  src/routes/dish.js
  src/routes/index.js
  yarn.lock
Labels: API

#70 Ahmadahmadalashtar/issue46 3
  src/__tests__/dish.test.js
  src/db/connection.js
  src/docs/Dish/dish.yaml
Labels: documentation, API, tests
