Repository HishamWattar/cooks-kingdom, pull requests merged in 2023-08, with the labels that each got.

#68 Customer order routes
  src/__tests__/cart.test.js
  src/controllers/cart.js
  src/docs/Cart/cart.yaml
  src/middlewares/validation.js
  src/routes/cart.js
  src/routes/index.js
Labels: API

#71 Feature: Add logging
  package.json
  src/app.js
  src/db/connection.js
  src/middlewares/error.js
  src/middlewares/validation.js
  src/utils/logger.js
  yarn.lock
Labels: setup

#74 Update README.md
  README.md
  src/assets/ahmad.jpg
  src/assets/db.png
  src/assets/docs.png
  src/assets/hisham.jpg
  src/assets/logo.png
  src/assets/mahmoud.jpg
  src/assets/rawan.png
  src/assets/system.png
  src/assets/zak.jpg
Labels: documentation

#77 Ahmadalashtar/issue61
  src/controllers/dish.js
  src/middlewares/auth.js
  src/routes/dish.js
Labels: Middleware, authorization

#93 Bugs: delete address
  src/__tests__/user.test.js
  src/controllers/user.js
Labels: bug

#96 Bugs: 3rd party authentication
  .env
  src/__tests__/admin.test.js
  src/__tests__/auth.test.js
  src/__tests__/cart.test.js
  src/__tests__/dish.test.js
  src/__tests__/review.test.js
  src/__tests__/user.test.js
  src/config/passport.js
  src/controllers/user.js
  src/docs/Admin/admin.yaml
  src/docs/Auth/localAuth.yaml
  src/middlewares/validation.js
  src/models/user.js
Labels: bug

#98 Bugs: cart endpoints
  src/__tests__/cart.test.js
  src/controllers/cart.js
  src/docs/Cart/cart.yaml
  src/routes/cart.js
Labels: bug

#100 Bugs: dish
  src/__tests__/dish.test.js
  src/controllers/dish.js
  src/docs/Dish/dish.yaml
  src/models/dish.js
  src/routes/dish.js
Labels: bug

#99 Bugs: review
  src/__tests__/review.test.js
  src/controllers/review.js
  src/docs/Review/review.yaml
  src/middlewares/validation.js
  src/routes/review.js
Labels: bug

#105 Bugs: order endpoints
  src/__tests__/order.test.js
  src/controllers/order.js
  src/docs/Order/order.yaml
  src/middlewares/validation.js
  src/models/order.js
  src/routes/order.js
Labels: bug

#108 Refactor the code
  src/__tests__/admin.test.js
  src/__tests__/auth.test.js
  src/__tests__/cart.test.js
  src/__tests__/dish.test.js
  src/__tests__/review.test.js
  src/__tests__/user.test.js
  src/controllers/admin.js
  src/controllers/auth.js
  src/controllers/dish.js
  src/controllers/user.js
  src/docs/Admin/admin.yaml
  src/docs/Cart/cart.yaml
  src/docs/Order/order.yaml
  src/docs/Review/review.yaml
  src/docs/User/user.yaml
  src/middlewares/auth.js
  src/routes/cart.js
  src/routes/review.js
Labels: refactoring

#115 Refactor: dish swagger documentation
  src/docs/Dish/dish.yaml
Labels: refactoring

#117 Update images
  src/assets/db.png
  src/assets/docs.png
  src/assets/system.png
Labels: documentation
